### ISSUE TITLE
Command 'install' exits with unexpected error: install: link: ... to ...: File exists

### ISSUE THREAD

**Issue by wq9578** [markjdb/freebsd#3]
The utility `install` claims that a file exists although it didn't exist before.
In a shell script `install` is called with a filename argument based on a UTC timestamp:

```
ls -al /etc/chrony.conf.utc_*

-rw-r--r--  1 root  wheel  3806 Oct  7 01:47 /etc/chrony.conf.utc_2024_10_06_235200.bak
-rw-r--r--  1 root  wheel  3814 Oct  7 01:52 /etc/chrony.conf.utc_2024_10_06_235309.bak

install -bCSv -B .utc_2024_10_06_235355.bak -o root -g wheel -m u=rw,go=r /my/path/chrony.conf /etc/chrony.conf

install: /etc/chrony.conf -> /etc/chrony.conf.utc_2024_10_06_235355.bak
Error: a command has a non-zero exit status
install: link: /etc/chrony.conf to /etc/chrony.conf.utc_2024_10_06_235355.bak: File exists
```

My guess is that there might be an implementation problem when combining the options `-b` (backup) and `-S` (safe copy), such that the file is created by the utility itself, causing a collision.
The [source](https://github.com/apple-oss-distributions/file_cmds/blob/6b3b4403a5e9f4db7b904a795bcfe9f2c321c821/install/install.plist.part#L7) used by current macOS 15.0.1 is taken from the [FreeBSD source tree](https://cgit.freebsd.org/src/tree/usr.bin/xinstall?id=f44e2577120c60cd92f685037bbb63127e0091e4) with the last commit [here](https://cgit.freebsd.org/src/commit/usr.bin/xinstall/xinstall.c?id=2f44f86575f9cba5da28b762c359f7a806400744).
[This line](https://github.com/markjdb/freebsd/blob/a56a5cc105a53705f651725586be60775df66d54/usr.bin/xinstall/xinstall.c#L974) is the nearest code point I could find.

**Comment by markjdb** [comment]
This isn't the right place to report a MacOS bug.
